services:
  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:2-watch
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    ports:
      - "8080:8080"
    networks:
      - auth-tier
      - api-tier
    volumes:
      - ./config/krakend/krakend.json:/etc/krakend/krakend.json

  auth:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - auth-tier
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import

  simple-api:
    build:
      context: ./simple-api
      target: runtime
    # ports:
    #   - "4001:3000"
    #   - "4002:3001"
    networks:
      - api-tier

  web:
    build:
      context: images/spa-auth-web
    ports:
      - "4000:3000"
    networks:
      - api-tier

networks:
  auth-tier:
  api-tier:
